version: "3"

services:
  db:
    image: "postgres:13.7-alpine"
    container_name: "rzd_collector_db"
    env_file:
      - collector_db.env
    ports:
      - "${COLLECTOR_APP_DB_PORT:-16240}:5432"
    volumes:
      - dbdata:/var/lib/postgresql/13/data
    restart: always
  collector_app:
    image: "rzd_tickets_monitor"
    container_name: "rzd_collector_app"
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - collector_app.env
    command: python run_collector.py
    restart: always
    depends_on:
      - db
    network_mode: host
volumes:
  dbdata:
