version: "3"

services:
  db:
    image: "postgres:14.3-alpine3.16"
    container_name: "rzd_collector_db"
    env_file:
      - collector_db.env
    ports:
      - "${COLLECTOR_APP_DB_PORT:-16240}:5432"
    volumes:
      - dbdata:/var/lib/postgresql/14/data
    restart: always
  collector_app:
    image: "rzd_collector_app"
    build:
      context: .
      dockerfile: ./Dockerfile.collector_app
    env_file:
      - collector_app.env
    command: python3.10 run_bot.py
    restart: always
    depends_on:
      - db
    network_mode: host
    platform: linux/amd64
volumes:
  dbdata:
