import os


SUGGEST_DIRECTIONS = ['МОСКВА', 'САНКТ-ПЕТЕРБУРГ', 'ЧЕРЕПОВЕЦ 1']
SUGGEST_TYPES = ['Плац', 'Купе', 'Сид']
SUGGEST_COUNT = [str(i) for i in range(1, 4)]

DEFAULT_MARKUP_BUTTONS = ['/set', '/cancel', '/status']

API_TOKEN_ENV = 'RZD_TICKETS_MONITOR_BOT_TOKEN'
PROXY_URL_ENV = 'RZD_TICKETS_MONITOR_BOT_PROXY'
API_TOKEN = os.getenv(API_TOKEN_ENV)
PROXY_URL = os.getenv(PROXY_URL_ENV)
LOGS_CHANNEL = os.getenv('RZD_TICKETS_MONITOR_BOT_LOGS_CHANNEL')
MAX_TRAINS_PER_MESSAGE = 15

COMMAND_SYMBOL = '@'

DATE_FORMAT = '%d.%m.%Y'
DATES_INTERVAL = 121

MIN_SUGGESTS_SIMILARITY = 70
SUGGESTS_LIMIT = 5

__all__ = [
    'API_TOKEN',
    'API_TOKEN_ENV',
    'MAX_TRAINS_PER_MESSAGE',
    'PROXY_URL',
    'PROXY_URL_ENV',
    'SUGGEST_COUNT',
    'SUGGEST_DIRECTIONS',
    'SUGGEST_TYPES',
    'DATES_INTERVAL',
    'DATE_FORMAT',
    'MIN_SUGGESTS_SIMILARITY',
    'SUGGESTS_LIMIT',
]
